version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_schema
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_secret
    ports:
      - "3306:3306"
    container_name: my_db
